# fly.toml app configuration file generated for 1663 on 2023-10-11T14:45:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "1663"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
